humfrey/update/urls.py
from django.conf.urls import url

from humfrey.update import views

app_name = "update"

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), {}, 'index'),
    url(r'^create/$', views.DefinitionDetailView.as_view(), name='definition-create'),
    url(r'^(?P<slug>[a-z\d\-]+)/$', views.DefinitionDetailView.as_view(), name='definition-detail'),
    url(r'^(?P<slug>[a-z\d\-]+)/log/$', views.UpdateLogListView.as_view(), name='log-list'),
    url(r'^(?P<slug>[a-z\d\-]+)/log/(?P<id>\d+)/$', views.UpdateLogDetailView.as_view(), name='log-detail'),
]

humfrey/update/models.py
import base64
import datetime
import logging
import pickle

from django_celery_beat.models import PeriodicTask, CrontabSchedule

try:
    import simplejson as json
except ImportError:
    import json

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from humfrey.sparql.models import Store
from humfrey.update.utils import evaluate_pipeline

DEFINITION_STATUS_CHOICES = (
    ('idle', 'Idle'),
    ('queued', 'Queued'),
    ('active', 'Active'),
)


class UpdateDefinitionAlreadyQueued(AssertionError):
    pass


class UpdateDefinition(models.Model):
    slug = models.SlugField(primary_key=True)
    title = models.CharField(max_length=80)
    description = models.TextField(blank=True)

    owner = models.ForeignKey(User, related_name='owned_updates', on_delete=models.CASCADE)

    cron_schedule = models.TextField(blank=True)
    periodic_task = models.ForeignKey(PeriodicTask, null=True, blank=True, on_delete=models.CASCADE)

    status = models.CharField(max_length=10, choices=DEFINITION_STATUS_CHOICES, default='idle')
    last_log = models.ForeignKey('UpdateLog', null=True, blank=True, on_delete=models.CASCADE)

    last_queued = models.DateTimeField(null=True, blank=True)
    last_started = models.DateTimeField(null=True, blank=True)
    last_completed = models.DateTimeField(null=True, blank=True)

    depends_on = models.ManyToManyField('self', symmetrical=False, blank=True)

    class Meta:
        ordering = ('title',)
        permissions = (
            ("view_updatedefinition", "Can view the update definition"),
            ("execute_updatedefinition", "Can perform an update"),
            ("administer_updatedefinition", "Can administer an update definition"),
            ("viewlogs_updatedefinition", "Can view the logs for an update definition"),
        )

    def queue(self, silent=False, trigger=None, user=None, forced=False):
        if self.status != 'idle':
            if silent:
                return
            raise UpdateDefinitionAlreadyQueued()
        self.status = 'queued'
        self.last_queued = datetime.datetime.now()

        update_log = UpdateLog.objects.create(update_definition=self,
                                              user=user,
                                              trigger=trigger or '',
                                              queued=self.last_queued,
                                              forced=forced)

        self.last_log = update_log
        self.save()

        from humfrey.update import tasks
        tasks.update.delay(update_log_id=update_log.id, slug=self.slug, trigger=trigger)
        return update_log

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('update:definition-detail', args=[self.slug])

    def __init__(self, *args, **kwargs):
        super(UpdateDefinition, self).__init__(*args, **kwargs)
        self._original_cron_schedule = self.cron_schedule

    def save(self, *args, **kwargs):
        if self.cron_schedule != self._original_cron_schedule and self.cron_schedule:
            minute, hour, day_of_week = self.cron_schedule.split()[:3]

            if not self.periodic_task:
                periodic_task = PeriodicTask(task='humfrey.update.update',
                                                  kwargs=json.dumps({'slug': self.slug,
                                                                     'trigger': 'crontab'}),
                                                  name='Update definition: {0}'.format(self.slug),
                                                  enabled=True)
                periodic_task.save()
                self.periodic_task = periodic_task

            crontab = self.periodic_task.crontab or CrontabSchedule()
            crontab.minute = minute
            crontab.hour = hour
            crontab.day_of_week = day_of_week
            crontab.save()

            self.periodic_task.crontab = crontab
            self.periodic_task.save()

            super(UpdateDefinition, self).save(*args, **kwargs)

        elif self.cron_schedule != self._original_cron_schedule and self.periodic_task:
            periodic_task, self.periodic_task = self.periodic_task, None

            super(UpdateDefinition, self).save(*args, **kwargs)

            periodic_task.crontab.delete()
            periodic_task.delete()
        else:
            super(UpdateDefinition, self).save(*args, **kwargs)


    def delete(self, *args, **kwargs):
        super(UpdateDefinition, self).delete(*args, **kwargs)
        if self.periodic_task:
            self.periodic_task.crontab.delete()
            self.periodic_task.delete()


class WithLevels(object):
    levels = {'errors': {'label': 'errors',
                         'icon': 'gnome-icons/32x32/dialog-error.png'},
              'warnings': {'label': 'warnings',
                           'icon': 'gnome-icons/32x32/dialog-warning.png'},
              'success': {'label': 'success',
                          'icon': 'gnome-icons/32x32/emblem-default.png'},
              'inprogress': {'label': 'in progress',
                             'icon': 'gnome-icons/32x32/system-run.png'},
              'waiting': {'label': 'waiting',
                          'icon': 'gnome-icons/32x32/dialog-question.png'}}

    @property
    def level(self):
        level = self.log_level
        if level is None:
            return 'waiting'
        if level >= logging.ERROR:
            return 'errors'
        elif level >= logging.WARNING:
            return 'warnings'
        elif level >= 0:
            return 'success'
        else:
            return 'inprogress'

    def get_level_display(self):
        return self.levels[self.level]['label']

    def get_level_icon(self):
        return self.levels[self.level]['icon']


class UpdateLog(models.Model, WithLevels):
    update_definition = models.ForeignKey(UpdateDefinition, related_name="update_log", on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='update_log', blank=True, null=True, on_delete=models.CASCADE)
    forced = models.BooleanField(default=False)

    trigger = models.CharField(max_length=80, blank=True)
    log_level = models.SmallIntegerField(null=True, blank=True)
    log = models.TextField()

    queued = models.DateTimeField(null=True, blank=True)
    started = models.DateTimeField(null=True, blank=True)
    completed = models.DateTimeField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse('update:log-detail', args=[self.update_definition.slug, self.id])

    @property
    def records(self):
        return self.updatelogrecord_set.all().order_by('when')


    def __str__(self):
        return '%s at %s' % (self.update_definition, self.queued)


class UpdatePipeline(models.Model):
    update_definition = models.ForeignKey(UpdateDefinition, related_name="pipelines", on_delete=models.CASCADE)
    value = models.TextField()
    stores = models.ManyToManyField(Store)

    def save(self, *args, **kwargs):
        try:
            evaluate_pipeline(self.value)
        except (SyntaxError, NameError) as e:
            raise ValueError(e)
        return super(UpdatePipeline, self).save(*args, **kwargs)


class UpdateVariable(models.Model):
    update_definition = models.ForeignKey(UpdateDefinition, related_name="variables", on_delete=models.CASCADE)
    name = models.TextField()
    value = models.TextField()


class Credential(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    url = models.CharField(max_length=4096, verbose_name="Base URL")
    username = models.CharField(max_length=128)
    password = models.CharField(max_length=4096)

humfrey/update/templates/update/base.html
{% extends "base.html" %}

{% block extra_head %}{{ block.super }}
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}update/base.css"/>
{% endblock %}

humfrey/update/templates/update/definition-deleted.html
{% extends "update/base.html" %}

{% block title %}Definition deleted: {{ object.title }}{% endblock %}

{% block content %}
  <h1>Definition deleted</h1>
  
  <p>The definition <em>{{ object.title }}</em> has been deleted.
{% endblock %}

humfrey/update/templates/update/definition-detail.html
{% extends "update/base.html" %}{% load humfrey_update %}

{% block title %}Update definition: {{ object.title|default:"Create" }}{% endblock %}

{% block content %}
  <h1>{{ object.title|default:"Create update definition" }}</h1>
  
  <form method="post" action="">{% csrf_token %}
  
  <table>
    <tbody>
      {{ form }}
    </tbody>
  </table>
  
  <section>
    <h2>Update pipelines</h2>
    
    {{ pipelines.management_form }}
    
  <table class="update-pipelines">
    <thead>
      <tr>
        <th class="update-pipeline-delete">Remove</th>
        <th class="update-pipeline-value">Pipeline</th>
        <th class="update-pipeline-stores">Stores</th>
      </tr>
    </thead>
    <tbody>
  {% for pipeline in pipelines.forms %}
      <tr>
        <td class="update-pipeline-delete">{{ pipeline.DELETE }}{{ pipeline.id }}</td>
        <td class="update-pipeline-value">{{ pipeline.value }}</td>
        <td class="update-pipeline-stores">{{ pipeline.stores }}</td>
        <td class="update-pipeline-errors">{{ pipeline.errors }}</td>
      </tr>
  {% endfor %}
    </tbody>
  </table>

  {% if "change_updatedefinition" in perms %}
    <input type="submit" name="action" value="{{ object.pk|yesno:"Update,Create" }}"/>
  {% endif %}
  {% if "delete_updatedefinition" in perms %}
    <div style="float:right">
      <input type="submit" name="action" value="Delete"/>
    </div>
  {% endif %}
  
  </form>
{% endblock %}

humfrey/update/templates/update/definition-queued.html
{% extends "update/base.html" %}

{% block title %}Queue for update: {{ object.title }}{% endblock %}

{% block content %}
  <h1>{{ object.title }}: Queue for update</h1>
  
  <p>
{% if success %}
    The update was successfully added to the execution queue.
{% else %}
    The update is already active, and was not queued again.
{% endif %}
  </p>
  
  <p>You may wish to <a href="{% url "update:index" %}">return to the
     dataset updater page</a> or the
     <a href="{{ update_log.get_absolute_url }}">log page</a>.</p>
{% endblock %}

humfrey/update/templates/update/index.html
{% extends "update/base.html" %}{% load humfrey_update %}{% load guardian_tags %}

{% block title %}Updater status{% endblock %}

{% block extra_head %}{{ block.super }}
<style type="text/css">
ul.update-definitions {
  list-style: none;
  padding-left: 0;
  margin-left: 0;
}

ul.update-definitions li {
  margin:2px 1em 1em 2px;
  padding:5px;
  border:1px solid #006699;
  width:300px;
  float:left;
}

ul.update-definitions li h3 {
  margin: 0;
  font-size:1em;
}

ul.update-definitions li p {
  margin:4px 0 4px 0;
}

</style>
{% endblock %}

{% block content %}
  <h1>Update status</h1>
  
  <section>
    <h2>Update definitions</h2>

    <table class="update-definitions">
      <thead>
        <tr>
          <th></th>
          <th>Identifier</th>
          <th>Name</th>
          <th>Last queued</th>
          <th>Last started</th>
          <th>Last completed</th>
          <th>State</th>
          <th>Edit</th>
          <th>Log</th>
          <th>Execute</th>
      <tbody>
    {% for definition in update_definitions %}{% get_obj_perms request.user for definition as "definition_perms" %}
        <tr class="outcome-{{ definition.last_log.level }}">
          <td>
            <a href="{{ definition.last_log.get_absolute_url }}">
              <img src="{{ STATIC_URL }}{{ definition.last_log.get_level_icon }}" alt="{{ definition.last_log.get_level_display|capfirst }}" title="{{ definition.last_log.get_outcome_display|capfirst }}"/>
            </a>
          </td>
          <td>{{ definition.slug }}</td>
          <td>{{ definition.title }}</td>
          <td>{{ definition.last_queued|timesince }} ago</td>
          <td>{{ definition.last_started|timesince }} ago</td>
          <td>{{ definition.last_completed|timesince }} ago</td>
          <td>{{ definition.get_status_display }}</td>
          <td>{% if 'change_updatedefinition' in definition_perms %}
            <a href="{% url "update:definition-detail" definition.slug %}">Edit</a>
          {% endif %}</td>
          <td><a href="{% url "update:log-list" definition.slug %}">Log</a></td>
          <td>{% if 'execute_updatedefinition' in definition_perms %}{% if definition.status == 'idle' %}
            <form method="post" action="{% url "update:definition-detail" definition.slug %}">{% csrf_token %}
              <input type="hidden" name="action" value="execute"/>
              <input type="submit" value="Queue for execution"/>
            </form>
          {% else %}
            Already queued
          {% endif %}{% endif %}</td>
        </tr>
    {% empty %}
        <tr>
          <td colspan="7">{% if perms.update.view_updatedefinition %}
            There are not yet any update definitions
          {% else %}
            There are not yet any update definitions that you can view
          {% endif %}</td>
        </tr>
    {% endfor %}
      </tbody>{% if perms.update.add_updatedefinition %}
      <tfoot>
        <tr>
          <td colspan="5"><a href="{% url "update:definition-create" %}">Create new</a></td>
        </tr>
      </tfoot>{% endif %}
    </table>
    
    
    <div style="clear:both;"/>
  </section>

{% endblock %}

humfrey/update/templates/update/log-detail.html
{% extends "update/base.html" %}{% load humfrey_update %}

{% block title %}Log {{ log.id }} for {{ definition }}{% endblock %}

{% block extra_head %}{{ block.super }}
<style type="text/css">
    {% ansi2html_styles %}
</style>
{% endblock %}

{% block content %}
  <h1>Log {{ log.id }} for {{ definition }}</h1>
  
  <p><a href="{% url "update:log-list" definition.slug %}">Back to all logs for <em>{{ definition }}</em></a>
  
  <table>
    <tbody>
      <tr>
        <td rowspan="2"><img src="{{ STATIC_URL }}{{ log.get_outcome_icon }}" alt="{{ log.get_outcome_display }}"/></td>
        <th>Trigger</th>
        <th>User</th>
        <th>Queued</th>
        <th>Started</th>
        <th>Completed</th>
      </tr>
      <tr>
        <td>{{ log.trigger }}</td>
        <td>{{ log.user }}</td>
        <td>{{ log.queued }}</td>
        <td>{{ log.started }}</td>
        <td>{{ log.completed }}</td>
      </tr>
    </tbody>
  </table>

  <pre>{{ log.log|escape|ansi2html }}</pre>
{% endblock %} 

humfrey/update/templates/update/log-list.html
{% extends "update/base.html" %}

{% block title %}Logs for {{ definition.title }}{% endblock %}

{% block content %}
  <h1>Logs for <em>{{ definition.title }}</em></h1>
  
  <table class="update-logs">
    <thead>
      <tr>
        <th>Trigger</th>
        <th>User</th>
        <th>Queued</th>
        <th>Started</th>
        <th>Completed</th>
        <th>Outcome</th>
      </tr>
    </thead>
    <tbody>{% for log in logs %}
      <tr class="outcome-{{ log.level }}">
        <td>{{ log.trigger }}</td>
        <td>{{ log.user }}</td>
        <td>{{ log.queued }}</td>
        <td>{{ log.started }}</td>
        <td>{{ log.completed }}</td>
        <td>{{ log.get_level_display }}</td>
        <td><a href="{{ log.get_absolute_url }}">View</a></td>
      </tr>{% endfor %}
    </tbody>
  </table>
  
{% endblock %}